### ISSUE TITLE
Subtitles turn back on whenever I pause or unpause

### ISSUE THREAD

**Issue by Max-E** [NiceandGently/mate-mplayer#1]
Process to reproduce:
1. start playing a video with subtitles
2. hit "v" to suppress the subtitles
3. hit the spacebar to pause

Alternate process:
1. start playing a video with subtitles
2. pause with a subtitle visible
3. hit "v" to suppress the subtitles; the visible subtitle should disappear
4. hith the spacebar to unpause

Expected result:
subtitles stay off

Actual result:
subtitles turn back on

This is on Linux Mint 13/Ubuntu 12.04, but with newer dependencies manually installed from newer Ubuntu versions. If there's any more information I can provide, let me know.

**Comment by NiceandGently** [comment]
confirmed and fixed with https://github.com/NiceandGently/mate-mplayer/commit/914bc20150168dba20293448298285aafd4affcc
;)
new release comming soon

**Comment by NiceandGently** [comment]
i've released 1.0.9
